### ISSUE TITLE
env GOOS=windows GOARCH=amd64 go build uidemo.go

### ISSUE THREAD

**Issue by omac777** [andlabs/ui#155]
Before I start, here is my go version 1.7beta2 environment:
go version
go version devel +fca9fc5 Thu Jun 16 19:45:33 2016 +0000 linux/amd64

go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/loongson/Code"
GORACE=""
GOROOT="/home/loongson/go1.7beta2"
GOTOOLDIR="/home/loongson/go1.7beta2/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build780373348=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

NOTE THE BUILDING NATIVELY WITH JUST go build works and with the following:
env GOOS=linux GOARCH=amd64 go build uidemo.go

GOOD.

CROSS-COMPILING TO WINDOWS 64-BIT HOWEVER FAILS.
It seems I have to be on windows in order for this to compile successfully.

env GOOS=windows GOARCH=amd64 go build uidemo.go
# command-line-arguments

./uidemo.go:8: undefined: ui.Main
./uidemo.go:9: undefined: ui.NewEntry
./uidemo.go:10: undefined: ui.NewButton
./uidemo.go:11: undefined: ui.NewLabel
./uidemo.go:12: undefined: ui.NewVerticalBox
./uidemo.go:13: undefined: ui.NewLabel
./uidemo.go:17: undefined: ui.NewWindow
./uidemo.go:19: undefined: ui.Button
./uidemo.go:22: undefined: ui.Window
./uidemo.go:23: undefined: ui.Quit
./uidemo.go:23: too many errors

**Comment by andlabs** [comment]
You also need to set three additional environment variables:

1) `CGO_ENABLED=1`
2) `CC=exectuable-of-mingw-w64-gcc`
3) `CXX=executable-of-mingw-w64-g++`

For instance, on an Ubuntu system it would be

```
CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
```

The problem is that Go doesn't know how to cross compile cgo packages on its own; you have to tell it what compilers to use (and that you have those compilers in the first place).

**Comment by ringrid** [comment]
I have same question, my OS is Fedora 24, and I had installed mingw32 & mingw64.
When I execute command:
`CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build main.go`

the question is:
/usr/local/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-gcc failed: exit status 1
x86_64-w64-mingw32-gcc: error: unrecognized command line option '-rdynamic'

can you help me?

**Comment by omac777** [comment]
On 08/09/2016 03:25 AM, ringrid wrote:
> I have same question, my OS is Fedora 24, and I had installed mingw32 & mingw64.
> When I execute command:
> `CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build main.go`
> 
> the question is:
> /usr/local/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-gcc failed: exit status 1
> x86_64-w64-mingw32-gcc: error: unrecognized command line option '-rdynamic'
> 
> can you help me?

To see all that information and the context in which you're getting the
rror:
go build -v -x -work main.go

From there you can go into the temporary directory where it's trying to
build it and tweak stuff and build it with different switches...whatever
you want to try that's different.  At least it shows you what's going on
under the hood.  If you want more help, capture all that verbosity into
a file and put the out put into the mailing list.

**Comment by ringrid** [comment]
@omac777 It's userful for me, and I had solved my question，It need other two packages: mingw64-gtk3 mingw64-winpthreads-static
Thanks a lot

**Comment by andlabs** [comment]
You should not need mingw64-gtk3. The Windows code does not use GTK+ 3.

**Comment by ringrid** [comment]
@andlabs yes, thank you. I removed mingw64-gtk3 and compiled succeed. awesome project!

**Comment by txthinking** [comment]
@andlabs 
How about on MacOS.
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tx/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sr/ysfcj49s52dg1fdb61fmj7wm0000gn/T/go-build221482393=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
```
$ CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build demo.go
# runtime/cgo
/usr/local/Cellar/go/1.7.3/libexec/src/runtime/cgo/gcc_libinit_windows.c:7:10: fatal error: 'windows.h' file not found
```

thanks.

**Comment by andlabs** [comment]
You need to set `$CC` to a MinGW-w64 cross-compiler. These exist on OS X; I don't see one in Homebrew...

**Comment by txthinking** [comment]
Thanks for your reply.
After i install MinGW-w64 i got this error
```
$ CGO_ENABLED=1 \
 GOOS=windows GOARCH=amd64 \
 CC=/usr/local/Cellar/mingw-w64/4.0.4/bin/x86_64-w64-mingw32-gcc\ 
 CXX=/usr/local/Cellar/mingw-w64/4.0.4/bin/x86_64-w64-mingw32-g++ \
 go build .
# github.com/andlabs/ui
../../../../andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
E:\github.com\andlabs\libui\build/E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2: error: ld returned 1 exit status
```

**Comment by sp-joseluis-ledesma** [comment]
Same error here. Crosscompiling from Linux to Windows:
`
# export GOOS=windows
# export GOARCH=amd64
# export CGO_ENABLED=1
# export CC=/usr/bin/x86_64-w64-mingw32-gcc
# export CXX=/usr/bin/x86_64-w64-mingw32-g++
# go build

vendor/github.com/andlabs/ui/libui_windows_amd64.a(stddialogs.cpp.obj): In function `msgbox':
E:\github.com\andlabs\libui\build/E:/github.com/andlabs/libui/windows/stddialogs.cpp:113: undefined reference to `__imp_TaskDialog'
collect2: error: ld returned 1 exit status
`

**Comment by andlabs** [comment]
You will need to upgrade to MinGW-w64 5.0.

**Comment by YamiOdymel** [comment]
After upgraded MinGW-w64 to 6.3.0, The error `undefined reference to '__imp_TaskDialog'` still exists on `macOS 10.12.2`

**Comment by andlabs** [comment]
How are you installing MinGW-w64?

**Comment by YamiOdymel** [comment]
Oops, sorry, I double checked the [README](https://github.com/cosmo0920/homebrew-mingw_w64) again, the `6.3.0` is actually the version of gcc, and the MinGW version is still `4.0.6`.

**Comment by andlabs** [comment]
Ah, all right. At least i do hope that there aren't still versions of MinGW-w64 5.0 or newer without the patch...

**Comment by andlabs** [comment]
I eventually decided that libui shouldn't have resources in static builds at all — they're just not supported in static libraries (presumably since they are global to the module you are linking the static library to). For the manifest this will make things a bit harder. I can provide a blank import for a generic manifest and then allow people to customize the manifest if they so choose, ensuring that the basics are still present. That rsrc tool seems interesting for the job...

Note to self: file libui issue about Windows icons automatically taking the first icon in the executable just like in Windows Explorer...

**Comment by Michael-Dixey** [comment]
@andlabs 
I know this thread is old, but I'm running into a similar issue when compiling for Linux from windows:
C:\go_tests\go_cfg_evd>go build -o form_test_linux formtest.go
# command-line-arguments
.\formtest.go:14:9: undefined: ui.Main
.\formtest.go:15:12: undefined: ui.NewEntry
.\formtest.go:16:15: undefined: ui.NewEntry
.\formtest.go:17:15: undefined: ui.NewEntry
.\formtest.go:19:13: undefined: ui.NewButton
.\formtest.go:20:18: undefined: ui.NewLabel
.\formtest.go:21:10: undefined: ui.NewVerticalBox
.\formtest.go:22:14: undefined: ui.NewLabel
.\formtest.go:24:14: undefined: ui.NewLabel
.\formtest.go:26:14: undefined: ui.NewLabel
.\formtest.go:26:14: too many errors

I've already set my GOOS variable to linux, and compiling for Windows from Windows does work correctly.  You had previously mentioned these 3 steps for Linux -> Windows: 
1. CGO_ENABLED=1
2. CC=exectuable-of-mingw-w64-gcc
3. CXX=executable-of-mingw-w64-g++
What would be the equivalent for Windows -> Linux?
Thanks

**Comment by andlabs** [comment]
CGO_ENABLED is the same. CC and CXX are the names of the executables of the cross-compiler toolchain, whatever that is. Yes, that means you will need a separate cross-compiler toolchain. You will also need to have a pkg-config set up for it, and GTK+ available to link to it. I don't know how to do any of that; sorry.

**Comment by Michael-Dixey** [comment]
Thanks for the prompt reply, I appreciate the info.  It seems it will probably be easier for me to just install these packages on my linux build and build the executable from there :). Thanks!
